USE [ISCA]
GO

CREATE SCHEMA CRS;
GO

CREATE TABLE [CRS].[Course](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Duration] [int] NOT NULL,
	[Title] [nvarchar](100) NOT NULL,
	[Code] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Course] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [CRS].[CourseInstance](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CourseId] [int] NOT NULL,
	[StartDate] [DATE] NOT NULL,
	FOREIGN KEY (CourseId) REFERENCES CRS.Course(Id)
)
GO

